config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  resources :comments

  resources :works
  root to: 'users#home'

  resources :orders

  resources :services

  post '/search', to: 'search#search'

  get '/cars_owners_documents/:user_id/new_document', to: 'cars_owners_documents#new_document', as: 'new_document'
  put '/cars_owners_documents/:user_id/add_document', to: 'cars_owners_documents#add_document', as: 'add_document'
  resources :cars_owners_documents
  
  resources :consumables

  get '/cars/:id/parts', to: 'cars#parts', as: 'parts'
  get '/cars/:id/new_part', to: 'cars#new_part', as: 'new_part'
  put '/cars/:id/add_part', to: 'cars#add_part', as: 'add_part'
  resources :cars

  get '/organizations/:id/services', to: 'organizations#services', as: 'organization_services'
  resources :organizations

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :users
end

app/models/service.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: services
#
#  id              :bigint           not null, primary key
#  name            :string           default("0"), not null
#  email           :string           not null
#  phone_number    :string           not null
#  address         :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  organization_id :bigint           not null
#
require 'elasticsearch/model'

class Service < ApplicationRecord
  include Elasticsearch::Model

  paginates_per 3

  belongs_to :organization

  has_many :services_works, dependent: :destroy
  has_many :works, through: :services_works
  has_many :comments, as: :commentable, dependent: :destroy

  validates :name, :email, :phone_number, :address, presence: true
  validates :name, uniqueness: true

  def name_in_one_word
    name.gsub(' ', '_')
  end

  def self.original_name(name)
    name.gsub('_', ' ')
  end

  def self.id_by_name(name)
    Service.find_by(name: name).id
  end

  def organization_service_works(organization_id:)
    scope = organizations_services_works_prices
            .where(organization_id: organization_id)
            .map(&:service_work_id)
    ServiceWork.find(scope)
  end

  def organization_service_work_price(organization_id:, service_work_id:)
    organizations_services_works_prices.find_by(organization_id: organization_id,
                                                service_work_id: service_work_id).price
  end
end

Service.__elasticsearch__.create_index!
Service.import

app/controllers/services_controller.rb
# frozen_string_literal: true

class ServicesController < ApplicationController
  before_action :set_service, only: %i[show edit update destroy]
  before_action :set_organization, only: %i[index show new create edit]

  def index
    @services = @organization.services.page params[:page]
    authorize @services
  end

  def show
    @comments = @service.comments.page params[:page]
    authorize @service
  end

  def new
    @service = Service.new
    authorize @service
  end

  def edit
    authorize @service
  end

  def create
    @service = Service.new(service_params)
    authorize @service

    if @service.save
      redirect_to service_path(@service, organization_id: @service.organization.id),
                  notice: 'Service was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    authorize @service
    if @service.update(service_params)
      redirect_to service_path(@service, organization_id: @service.organization.id),
                  notice: 'Service was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @service
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_service
    @service = Service.find(params[:id])
  end

  def set_organization
    @organization = Organization.find_by(id: params[:organization_id])
  end

  def service_params
    params.require(:service).permit(:name, :email, :address, :phone_number, :organization_id)
  end
end

app/helpers/services_helper.rb
# frozen_string_literal: true

module ServicesHelper
end

app/views/services/_form.html.erb
<%= simple_form_for(@service) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <%= f.hidden_field :organization_id, value: @organization.id %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form', service: @service,
                   organization: @organization %>

<%= link_to 'Back', services_path(organization_id: @organization.id) %>

app/views/services/index.html.erb
<%= @organization.name %> services:
<ul>
  <% @services.each do |service| %>
    <li><%= link_to service.name, service_path(service, organization_id: @organization) %></li>
  <% end %>  

  <%= paginate @services %>
</ul>

<%= link_to 'Add service', new_service_path(organization_id: @organization) if current_user.service_owner? || current_user.admin? %>

<form name='graphqlForm'>
  <%= hidden_field :authenticity_token, form_authenticity_token, name: :authenticity_token %>
</form>

<script>
  var graphqlFrom = () => {
    let form = document.forms.graphqlForm
    let formData = new FormData(graphqlForm)

    let idAttribute = form['authenticity_token'].getAttribute('id')
    let authenticationToken = idAttribute.replace('authenticity_token_', '')

    return {
      form,
      formData,
      authenticationToken
    }
  }
  var graphqlServices = () => `
    query {
      services(organizationId: 1) {
        name
        organization {
          name
          phoneNumber
          serviceOwner {
            firstName
            lastName
          }
        }
      }
    }
  `
  let graphqlFormDataSet = (formData, key, value) => { formData.set(key, value) }

  function services() {
    let { form, formData, authenticationToken } = graphqlFrom()
    let query = graphqlServices()

    graphqlFormDataSet(formData, 'query', query)
    graphqlFormDataSet(formData, 'authenticity_token', authenticationToken)

    fetch('/graphql', {
      method: 'POST',
      body: formData
    })
    .then(res => res.json())
    .then(data => { console.log(JSON.stringify(data)) })
  }

  services()
</script>

app/views/services/new.html.erb
<h1>New Service for <%= "#{@organization.name}" %></h1>

<%= render 'form', service: @service,
                   organization: @organization %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @service.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @service.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @service.address %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @service.phone_number %>
</p>
<hr>

Works: 
<ul>
  <% @service.works.each do |work| %>
    <li><%= work.title %>: <%= work.price_in_organization(@organization.id) %>$ |
    <%= link_to 'edit', edit_work_path(work, service_id: @service.id) %></li> |
    <%= link_to 'make order', new_order_path(work_id: work.id, service_id: @service.id) %></li>
  <% end %>
</ul>

<p>
  <strong>Comments:</strong>
  <%= render 'comments/form', commentable: @service %>
  <%= render 'comments/comments', comments: @comments %>
  <%= paginate @comments %>
</p>

<%= link_to 'Edit', edit_service_path(@service, organization_id: @organization.id) %> |
<%= link_to 'Back', services_path(organization_id: @organization.id) %>

<form name='graphqlForm'>
  <%= hidden_field :authenticity_token, form_authenticity_token, name: :authenticity_token %>
</form>

<script>
  var graphqlFrom = () => {
    let form = document.forms.graphqlForm
    let formData = new FormData(graphqlForm)

    let idAttribute = form['authenticity_token'].getAttribute('id')
    let authenticationToken = idAttribute.replace('authenticity_token_', '')

    return {
      form,
      formData,
      authenticationToken
    }
  }
  var graphqlWorks = () => `
    query {
      works(companyId: 1) {
        id
        title
        categoryId
      }
    }
  `

  var graphqlComments = () => `
    query {
      comments(orderId: 1) {
        content
        commentableType
        user {
          firstName
          lastName
        }
      }
    }
  `

  let graphqlFormDataSet = (formData, key, value) => { formData.set(key, value) }

  function executeQuery(query) {
    let { form, formData, authenticationToken } = graphqlFrom()

    graphqlFormDataSet(formData, 'query', query)
    graphqlFormDataSet(formData, 'authenticity_token', authenticationToken)

    fetch('/graphql', {
      method: 'POST',
      body: formData
    })
    .then(res => res.json())
    .then(data => { console.log(JSON.stringify(data)) })
  }

  let usersQuery = graphqlWorks()
  executeQuery(usersQuery)

  let commentsQuery = graphqlComments()
  executeQuery(commentsQuery)
</script>