config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  resources :comments

  resources :works
  root to: 'users#home'

  resources :orders

  resources :services

  post '/search', to: 'search#search'

  get '/cars_owners_documents/:user_id/new_document', to: 'cars_owners_documents#new_document', as: 'new_document'
  put '/cars_owners_documents/:user_id/add_document', to: 'cars_owners_documents#add_document', as: 'add_document'
  resources :cars_owners_documents
  
  resources :consumables

  get '/cars/:id/parts', to: 'cars#parts', as: 'parts'
  get '/cars/:id/new_part', to: 'cars#new_part', as: 'new_part'
  put '/cars/:id/add_part', to: 'cars#add_part', as: 'add_part'
  resources :cars

  get '/organizations/:id/services', to: 'organizations#services', as: 'organization_services'
  resources :organizations

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :users
end

app/models/organization.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: organizations
#
#  id               :bigint           not null, primary key
#  email            :string           not null
#  phone_number     :string           not null
#  address          :string           not null
#  name             :string           not null
#  service_owner_id :integer          not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
class Organization < ApplicationRecord
  paginates_per 2

  has_many :cities_organizations, dependent: :destroy
  has_many :cities, through: :cities_organizations

  has_many :services, dependent: :destroy

  has_many :organizations_works, dependent: :destroy
  has_many :works, through: :organizations_works

  has_many :comment, as: :commentable, dependent: :destroy

  belongs_to :service_owner

  validates :address, :email, :name, :phone_number, presence: true, uniqueness: true

  def all_services?
    services.count == Service.count
  end
end

app/controllers/organizations_controller.rb
# frozen_string_literal: true

class OrganizationsController < ApplicationController
  before_action :set_organization, only: %i[show edit destroy]
  before_action :set_cities, only: %i[new create edit]
  before_action -> { organization(organization_id: params[:id]) }, only: %i[create update]

  attr_accessor :service

  def index
    @organizations = Organization.all.page params[:page]
    authorize @organizations
  end

  def show
    authorize @organization
  end

  def new
    @organization = Organization.new
    authorize @organization
  end

  def edit
    authorize @organization
  end

  def services
    @services = @organization.services
  end

  def create
    authorize @organization
    if @organization.save
      redirect_to @organization, notice: 'Organization was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    authorize @organization
    if @organization.update(organization_params)
      redirect_to @organization, notice: 'Organization was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @organization
    if @organization.delete
      redirect_to organizations_url, notice: 'Organization was successfully destroyed.'
    else
      render :destroy, status: :unprocessable_entity
    end
  end

  private

  def set_organization
    @organization = Organization.find(params[:id])
  end

  def set_cities
    @cities = City.all
  end

  def organization(organization_id: nil)
    @organization = if organization_id
                      Organization.find_by(id: organization_id)
                    else
                      Organization.new(organization_params)
                    end
  end

  def organization_params
    params.require(:organization).permit(:service_owner_id, :email, :phone_number, :address, :name,
                                         city_ids: [])
  end

  def choosen_services
    params.require(:organization).permit(services: [])
    Service.find(params[:organization][:services].drop(1))
  end

  def organization_new_services
    services = params[:organization_services].keys.map do |name|
      Service.id_by_name(Service.original_name(name))
    end
    @services = Service.find(services)
  end

  def organization_new_services_works
    service_name = service.name_in_one_word
    service_works_id = params[:organization_services][service_name][:service_works].drop(1)
    @service_works = ServiceWork.find(service_works_id)
  end
end

app/helpers/organizations_helper.rb
# frozen_string_literal: true

module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= simple_form_for(organization) do |form| %>
  <% if organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
        <% organization.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :service_owner_id, value: current_user.id %>

  <%= form.input :email %>

  <%= form.input :phone_number %>

  <%= form.input :address %>

  <%= form.input :name %>

  <%= form.input :city_ids, label: 'Cities', as: :check_boxes, collection: cities, label_method: :name, value_method: :id %>

  <%= form.button :submit %>|
  <%= link_to 'Back', organizations_path %>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing Organization</h1>

<%= render 'form', organization: @organization, cities: @cities %>

app/views/organizations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Organizations</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Phone number</th>
      <th>Adress</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= organization.email %></td>
        <td><%= organization.phone_number %></td>
        <td><%= organization.address %></td>
        <td><%= organization.name %></td>
        <td><%= link_to 'Show', organization %></td>
        <td><%= link_to 'Edit', edit_organization_path(organization) if current_user.service_owner? || current_user.admin? %></td>
        <td><%= link_to 'Services', services_path(organization_id: organization.id) %></td>
        <td><%= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' } if current_user.service_owner? || current_user.admin? %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organization', new_organization_path if current_user.service_owner? || current_user.admin? %>
<%= paginate @organizations %>


<form name='graphqlForm'>
  <%= hidden_field :authenticity_token, form_authenticity_token, name: :authenticity_token %>
</form>

<script>
  var graphqlFrom = () => {
    let form = document.forms.graphqlForm
    let formData = new FormData(graphqlForm)

    let idAttribute = form['authenticity_token'].getAttribute('id')
    let authenticationToken = idAttribute.replace('authenticity_token_', '')

    return {
      form,
      formData,
      authenticationToken
    }
  }
  var graphqlOrganizations = () => `
    {
      organizations(serviceOwnerId: 2) {
        id
        name
        address
        email
        services {
          name
        }
        serviceOwner {
          firstName
        }
      }
    }
  `
  let graphqlFormDataSet = (formData, key, value) => { formData.set(key, value) }

  function cars() {
    let { form, formData, authenticationToken } = graphqlFrom()
    let query = graphqlOrganizations()

    graphqlFormDataSet(formData, 'query', query)
    graphqlFormDataSet(formData, 'authenticity_token', authenticationToken)

    fetch('/graphql', {
      method: 'POST',
      body: formData
    })
    .then(res => res.json())
    .then(data => { console.log(JSON.stringify(data)) })
  }

  cars()
</script>

app/views/organizations/new.html.erb
<h1>New Organization</h1>

<%= render 'form', organization: @organization, cities: @cities %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/new_services.html.erb
<h1>Add Organization Service</h1>

<%= form_with(url: organization_service_works_path(@organization), method: :get) do |form| %>

  <%= collection_check_boxes 'organization', 'services', @services, :id, :name %>
  <br>

  <%= form.submit 'Next'  %>
<% end %>

<%= link_to 'Back', organization_services_path(@organization) %>

app/views/organizations/service_works.html.erb
<%= form_with(url: add_organization_services_path(@organization), method: :post) do |form| %>
  <% @services.each do |service| %>
    <%= form.hidden_field service.name_in_one_word, value: service.id %>
    <strong><%= service.name %></strong>:
    <br>

    <%= collection_check_boxes "organization_services[#{service.name_in_one_word}]", 'service_works', @service_works, :id, :title %>
    <br>
  <% end %>

  <%= form.submit 'Add' %>
<% end %>

app/views/organizations/services.html.erb
<%= @organization.name %> services:
<ul>
  <% @services.each do |service| %>
    <li><%= service.name %></li>
  <% end %>
</ul>

<%= link_to 'Add service', new_organization_services_path(@organization) %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @organization.email %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @organization.phone_number %>
</p>

<p>
  <strong>Address:</strong>
  <%= @organization.address %>
</p>

<p>
  <strong>Name:</strong>
  <%= @organization.name %>
</p>

<p>
  <strong>Cities</strong>:<br> 
  <ul>
    <% @organization.cities.each do |city| %>
      <li><%= city.name %></li>
    <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>