config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  resources :comments

  resources :works
  root to: 'users#home'

  resources :orders

  resources :services

  post '/search', to: 'search#search'

  get '/cars_owners_documents/:user_id/new_document', to: 'cars_owners_documents#new_document', as: 'new_document'
  put '/cars_owners_documents/:user_id/add_document', to: 'cars_owners_documents#add_document', as: 'add_document'
  resources :cars_owners_documents
  
  resources :consumables

  get '/cars/:id/parts', to: 'cars#parts', as: 'parts'
  get '/cars/:id/new_part', to: 'cars#new_part', as: 'new_part'
  put '/cars/:id/add_part', to: 'cars#add_part', as: 'add_part'
  resources :cars

  get '/organizations/:id/services', to: 'organizations#services', as: 'organization_services'
  resources :organizations

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :users
end

app/models/car.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: cars
#
#  id                :bigint           not null, primary key
#  user_id           :integer
#  model             :string           default("a12"), not null
#  year_production   :integer          default(2000), not null
#  engine_volume     :integer          default(1), not null
#  mileage           :integer          default(0), not null
#  body_type         :string           default("sedan"), not null
#  maker             :string           default("bmw"), not null
#  vin               :string           default("123asdfaase123"), not null
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  fuel_type         :integer          default("electricity"), not null
#  transmission_type :integer          default("mechanic"), not null
#
class Car < ApplicationRecord
  paginates_per 2

  has_one_attached :photo

  has_many :cars_parts, dependent: :destroy
  has_many :parts, through: :cars_parts

  has_many :consumables
  has_many :orders

  belongs_to :user

  enum fuel_type: { electricity: 0, gas: 1, petrol: 2 }
  enum transmission_type: { mechanic: 0, automatic: 1 }

  validates :model, :year_production, :engine_volume,
            :mileage, :body_type, :fuel_type,
            :transmission_type, :maker, :vin,
            presence: true

  validates :vin, uniqueness: true
  validates :engine_volume,
            numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 3.5 }
  validates :fuel_type, inclusion: { in: Car.fuel_types.keys }
  validates :transmission_type, inclusion: { in: Car.transmission_types.keys }

  def all_parts?
    parts.size == Part.count
  end

  def car_name
    "#{maker}, #{model}, #{vin}"
  end
end

app/models/car_form.rb
# frozen_string_literal: true

class CarForm
  include ActiveModel::Model

  attr_accessor :model, :year_production,
                :engine_volume, :mileage,
                :body_type, :maker, :vin,
                :fuel_type, :transmission_type,
                :documents, :parts, :photo

  def initialize(car:)
    @model = car.model
    @year_production = car.year_production
    @engine_volume = car.engine_volume
    @mileage = car.mileage
    @body_type = car.body_type
    @maker = car.maker
    @vin = car.vin
    @fuel_type = car.fuel_type
    @transmission_type = car.transmission_type
    @photo = car.photo
  end
end

app/controllers/cars_controller.rb
# frozen_string_literal: true

class CarsController < ApplicationController
  before_action :set_car, only: %i[show edit update destroy parts new_part add_part]
  before_action :fuel_types,
                :set_photos,
                :transmission_types,
                :documents,
                only: %i[new edit]

  def index
    @cars = Car.all.page params[:page]
    authorize @cars
  end

  def show
    authorize @car
  end

  def new
    car = FactoryBot.build(:car)
    @car_form = CarForm.new(car: car)
    authorize car
  end

  def edit
    @car_form = CarForm.new(car: @car)
    authorize @car
  end

  def create
    @car = Car.new(car_params)
    if @car.save
      attach_photo(params[:photo])
      redirect_to @car, notice: 'Car was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    authorize @car
    if @car.update(car_params)
      redirect_to @car, notice: 'Car was successfully updated.'
    else
      redirect_to :edit_car, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @car
    @car.delete
    redirect_to cars_url, notice: 'Car was successfully destroyed.'
  end

  def parts; end

  def new_part
    @parts = Part.select { |part| part unless @car.parts.include?(part) }
  end

  def add_part
    @car.parts << new_car_parts
  end

  private

  def set_photos
    pexels_service = PexelsService.new(
      'bmw auto',
      size: :medium,
      orientation: :square
    )
    @photos = []
    3.times do |i|
      photo = pexels_service.photos[i].src['original']
      @photos.push(photo)
    end
  end

  def attach_photo(photo_src)
    pexels_service = PexelsService.new

    pexels_service.upload(photo_src)

    photo_name = pexels_service.photo_name_by_src(photo_src)
    photo_path = pexels_service.photo_path_by_src(photo_src)
    photo_file = File.open(photo_path)

    @car.photo.attach(io: photo_file, filename: photo_name)
  end

  def set_car
    @car = Car.find(params[:id])
  end

  def car_params
    params.require(:car_form).permit(:model, :year_production, :engine_volume,
                                     :mileage, :body_type, :fuel_type,
                                     :transmission_type, :maker, :vin,
                                     :user_id, :photo)
  end

  def new_car_parts
    parts_params = params.require(:car).permit(parts: [])
    new_parts_ids = parts_params.to_h[:parts].map { |id| id.to_i if id.present? }.uniq
    Part.select { |p| p if @car.parts.exclude?(p) && new_parts_ids.include?(p.id) }
  end

  def fuel_types
    @fuel_types = Car.fuel_types
  end

  def transmission_types
    @transmission_types = Car.transmission_types
  end

  def documents
    @documents = Document.names
  end
end

app/helpers/cars_helper.rb
# frozen_string_literal: true

module CarsHelper
end

app/views/cars/_documents.html.erb
<% documents.each do |d| %>
  <% form.label d.name %>
  <% form.date_field 'documents[]', name %>
<% end %>

app/views/cars/_form.html.erb
<%= simple_form_for(car_form, url: url, method: method) do |form| %>
  <% if car_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car_form.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
        <% car_form.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% @photos.each do |photo| %>
    <%= image_tag photo, class: 'car-photo' %>
    <%= radio_button_tag :photo, photo, false %>
  <% end %>
  <br>

  <%= form.input :photo, as: :file %>

  <% if @car_form.photo.attached? %>
    <%= image_tag @car_form.photo, class: 'car-photo' %>
  <% end %>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <%= form.input :model, required: true %>

  <%= form.input :year_production, required: true %>
  
  <%= form.input :engine_volume, required: true %>
  
  <%= form.input :mileage, required: true %>
  
  <%= form.input :body_type, required: true %>
  
  <%= form.input :fuel_type, collection: fuel_types, value_method: :first, include_blank: false %>
  
  <%= form.input :transmission_type, collection: transmission_types, value_method: :first, include_blank: false %>
  
  <%= form.input :maker, required: true %>
  
  <%= form.input :vin, required: true %>  
  
  <%= form.button :submit%>|
  <%= link_to 'Back', cars_path %>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car_form: @car_form,
                   fuel_types: @fuel_types,
                   transmission_types: @transmission_types,
                   url: car_path,
                   method: :put %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cars</h1>

<table>
  <thead>
    <tr>
      <th>Model</th>
      <th>Year production</th>
      <th>Engine volume</th>
      <th>Mileage</th>
      <th>Body type</th>
      <th>Fuel type</th>
      <th>Transmission type</th>
      <th>Maker</th>
      <th>Vin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.model %></td>
        <td><%= car.year_production %></td>
        <td><%= car.engine_volume %></td>
        <td><%= car.mileage %></td>
        <td><%= car.body_type %></td>
        <td><%= car.fuel_type %></td>
        <td><%= car.transmission_type %></td>
        <td><%= car.maker %></td>
        <td><%= car.vin %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Consumables', consumables_path(car_id: car.id) %></td>
        <td><%= link_to 'Parts', parts_path(car) %></td>
        <td><%= link_to 'Orders', orders_path(car_id: car.id) %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path %>

<%= paginate @cars %>

<form name='graphqlForm'>
  <%= hidden_field :authenticity_token, form_authenticity_token, name: :authenticity_token %>
</form>

<script>
  var graphqlFrom = () => {
    let form = document.forms.graphqlForm
    let formData = new FormData(graphqlForm)

    let idAttribute = form['authenticity_token'].getAttribute('id')
    let authenticationToken = idAttribute.replace('authenticity_token_', '')

    return {
      form,
      formData,
      authenticationToken
    }
  }
  var graphqlCars = () => `
    query {
      cars {
        vin
        maker
        mileage
      }
    }
  `
  let graphqlFormDataSet = (formData, key, value) => { formData.set(key, value) }

  function cars() {
    let { form, formData, authenticationToken } = graphqlFrom()
    let query = graphqlCars()

    graphqlFormDataSet(formData, 'query', query)
    graphqlFormDataSet(formData, 'authenticity_token', authenticationToken)

    fetch('/graphql', {
      method: 'POST',
      body: formData
    })
    .then(res => res.json())
    .then(data => { console.log(JSON.stringify(data)) })
  }

  cars()
</script>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car_form: @car_form,
                   fuel_types: @fuel_types,
                   transmission_types: @transmission_types,
                   photos:  @photos,
                   url: cars_path,
                   method: :post %>

<%= link_to 'Back', cars_path %>

app/views/cars/new_part.html.erb
<%= form_with(url: add_part_path(id: @car.id), method: :put) do |form| %>
  <%= form.collection_check_boxes 'car[parts]', @parts, :id, :name%>
  <br>

  <%= form.submit 'Add'  %>
<% end %>

app/views/cars/parts.html.erb
<ul>
  <% @car.parts.each do |part| %> 
    <li><%= part.name %></li>
  <% end %>
</ul>


<%= link_to('Add part', new_part_path(@car)) unless @car.all_parts? %>


<form name='graphqlForm'>
  <%= hidden_field :authenticity_token, form_authenticity_token, name: :authenticity_token %>
</form>

<script>
  var graphqlFrom = () => {
    let form = document.forms.graphqlForm
    let formData = new FormData(graphqlForm)

    let idAttribute = form['authenticity_token'].getAttribute('id')
    let authenticationToken = idAttribute.replace('authenticity_token_', '')

    return {
      form,
      formData,
      authenticationToken
    }
  }
  var graphqlConsumables = () => `
    {
      parts(carId: 2) {
        name
      }
    }
  `
  let graphqlFormDataSet = (formData, key, value) => { formData.set(key, value) }

  function cars() {
    let { form, formData, authenticationToken } = graphqlFrom()
    let query = graphqlConsumables()

    graphqlFormDataSet(formData, 'query', query)
    graphqlFormDataSet(formData, 'authenticity_token', authenticationToken)

    fetch('/graphql', {
      method: 'POST',
      body: formData
    })
    .then(res => res.json())
    .then(data => { console.log(JSON.stringify(data)) })
  }

  cars()
</script>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<% if @car.photo.attached? %>
  <%= image_tag @car.photo, class: 'car-photo' %>
  <br>
<% end %>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Year production:</strong>
  <%= @car.year_production %>
</p>

<p>
  <strong>Engine volume:</strong>
  <%= @car.engine_volume %>
</p>

<p>
  <strong>Mileage:</strong>
  <%= @car.mileage %>
</p>

<p>
  <strong>Body type:</strong>
  <%= @car.body_type %>
</p>

<p>
  <strong>Fuel type:</strong>
  <%= @car.fuel_type %>
</p>

<p>
  <strong>Transmission type:</strong>
  <%= @car.transmission_type %>
</p>

<p>
  <strong>Maker:</strong>
  <%= @car.maker %>
</p>

<p>
  <strong>Vin:</strong>
  <%= @car.vin %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

<form name='graphqlForm'>
  <%= hidden_field :authenticity_token, form_authenticity_token, name: :authenticity_token %>
</form>

<script>
  var graphqlFrom = () => {
    let form = document.forms.graphqlForm
    let formData = new FormData(graphqlForm)

    let idAttribute = form['authenticity_token'].getAttribute('id')
    let authenticationToken = idAttribute.replace('authenticity_token_', '')

    return {
      form,
      formData,
      authenticationToken
    }
  }
  var graphqlUserByIdQuery = (id) => `
    query {
      user(id: ${id}) {
        id
        firstName
        lastName
      }
    }
  `
  let graphqlFormDataSet = (formData, key, value) => { formData.set(key, value) }

  function userById(id) {
    let { form, formData, authenticationToken } = graphqlFrom()
    let query = graphqlUserByIdQuery(id)

    graphqlFormDataSet(formData, 'query', query)
    graphqlFormDataSet(formData, 'authenticity_token', authenticationToken)

    fetch('/graphql', {
      method: 'POST',
      body: formData
    })
    .then(res => res.json())
    .then(data => { console.log(JSON.stringify(data)) })
  }

  userById(1)
</script>

app/views/cars/some.html.erb
<p id="notice"><%= notice %></p>

<% if @car.photo.attached? %>
  <%= image_tag @car.photo, class: 'car-photo' %>
  <br>
<% end %>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

<form name='graphqlForm'>
  <%= hidden_field :authenticity_token, form_authenticity_token, name: :authenticity_token %>
</form>

<script>
  var graphqlFrom = () => {
    let form = document.forms.graphqlForm
    let formData = new FormData(graphqlForm)

    let idAttribute = form['authenticity_token'].getAttribute('id')
    let authenticationToken = idAttribute.replace('authenticity_token_', '')

    return {
      form,
      formData,
      authenticationToken
    }
  }
  var graphqlUserByIdQuery = (id) => `
    query {
      user(id: ${id}) {
        id
        firstName
        lastName
      }
    }
  `
  let graphqlFormDataSet = (formData, key, value) => { formData.set(key, value) }

  function userById(id) {
    let { form, formData, authenticationToken } = graphqlFrom()
    let query = graphqlUserByIdQuery(id)

    graphqlFormDataSet(formData, 'query', query)
    graphqlFormDataSet(formData, 'authenticity_token', authenticationToken)

    fetch('/graphql', {
      method: 'POST',
      body: formData
    })
    .then(res => res.json())
    .then(data => { console.log(JSON.stringify(data)) })
  }

  userById(1)
</script>